apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: integration-suite-test-component-git-source-tgrk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: integration-suite-test-component-git-source-tgrk
    app.kubernetes.io/part-of: integ-app-xhvj
  name: integration-suite-test-component-git-source-tgrk
  namespace: integration-e2e-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: integration-suite-test-component-git-source-tgrk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: integration-suite-test-component-git-source-tgrk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:ef01b77d5ed44196a804d80aa4a84808
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
